apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jump
spec:
  provider: vault
  secretObjects:
  - secretName: jump
    type: Opaque
    data: 
    - objectName: OWMAPIKEY
      key: OWMAPIKEY
    - objectName: LATLONG
      key: LATLONG
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: jump
    objects: |
      - objectName: "OWMAPIKEY"
        secretPath: "apps-kv/data/jump/config"
        secretKey: "OWMAPIKEY"
      - objectName: "LATLONG"
        secretPath: "apps-kv/data/jump/config"
        secretKey: "LATLONG"
